# Generated by Django 4.1.4 on 2022-12-08 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='full_name')),
                ('image', models.ImageField(upload_to='student_images/', verbose_name='image')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='phone_number')),
                ('join_on', models.DateTimeField(auto_now_add=True, verbose_name='join_on')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Student',
            },
        ),
    ]
