# Generated by Django 4.1.4 on 2022-12-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoGetOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='full_name')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('coupon', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'WhoGetOffer',
            },
        ),
    ]
