# Generated by Django 4.1.4 on 2022-12-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0004_alter_whogetoffer_full_name_alter_whogetoffer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whogetoffer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
