# Generated by Django 4.1.4 on 2022-12-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0005_alter_whogetoffer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(upload_to='course_images/', verbose_name='image')),
                ('price', models.IntegerField(default=0, verbose_name='price')),
                ('discound', models.IntegerField(default=0, verbose_name='discound')),
                ('instructor', models.CharField(max_length=150, verbose_name='instructor')),
            ],
            options={
                'verbose_name_plural': 'Course',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('disvalue', models.IntegerField(verbose_name='disvalue')),
            ],
            options={
                'verbose_name_plural': 'Offer',
            },
        ),
    ]
