# Generated by Django 4.1.4 on 2022-12-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0006_course_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='galary_images/', verbose_name='image')),
            ],
            options={
                'verbose_name_plural': 'Galary',
            },
        ),
    ]
